name: Docker GCP deployment

on:
  push:
    branches:
      - github-action-workflow
  workflow_dispatch:

jobs:
  lint-test:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
    secrets: inherit

  build:
    needs: lint-test
    uses: ./.github/workflows/workflow-build-container.yml
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/workflow-deploy-gcp.yml
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit
