name: Docker GCP deployment

on:
  push:
    branches:
      - github-action-workflow
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/workflow-lint-test-python.yml

  build:
    needs: test
    uses: ./.github/workflows/workflow-build-container.yml
    with:
      container-name: fastapi-example
      tag: latest

  #deploy:
   # needs: build
    #uses: ./.github/workflows/workflow-deploy.yml@main
    #with:
     # image: northamerica-northeast1-docker.pkg.dev/cfia-ai-lab-gcp-project/cfia-ai-lab-docker-repo/fastapi-example:latest
