name: Docker GCP deployment

on:
    push:
        branches:
          - github-action-workflow
    workflow_dispatch:

# jobs:       
#     lint-test:
#         uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
#         secrets: inherit
#     build:
#         needs: lint-test
#         uses: ai-cfia/github-workflows/.github/workflows/workflow-build-container.yml@main
#         with:
#           container-name: ${{ github.event.repository.name }}
#           tag: ${{ github.sha }}
#         secrets: inherit

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GAR
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.GCP_CLOUDRUN_REGION }}-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.LOUIS_GAR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.GCP_CLOUDRUN_REGION }}-docker.pkg.dev/${{ secrets.LOUIS_REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}

    - name: Logout from GAR
      run: docker logout ${{ secrets.GCP_CLOUDRUN_REGION }}-docker.pkg.dev
