name: Docker GCP deployment

on:
  push:
    branches:
      - github-action-workflow
  workflow_dispatch:

jobs:
  lint-test:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
    secrets: inherit

  build:
        needs: lint-test
        runs-on: ubuntu-latest
        steps:
          - name: Login to GAR
            uses: docker/login-action@v2
            with:
              registry: ${{ secrets.GCP_CLOUDRUN_REGION }}-docker.pkg.dev
              username: _json_key
              password: ${{ secrets.LOUIS_GAR_JSON_KEY }}
          - uses: actions/checkout@v2 
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          - name: Cache Docker layers
            uses: actions/cache@v2
            with:
              path: /tmp/.buildx-cache
              key: ${{ runner.os }}-${{ github.event.repository.name }}-${{ github.sha }}
              restore-keys: |
                ${{ runner.os }}-${{ github.event.repository.name }}
          - name: Build the Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: northamerica-northeast1-docker.pkg.dev/cfia-ai-lab-gpc-project/docker-repo-cfia-ai-lab/fastapi-example:latest
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache-new
          - name: Move cache
            run: |
              rm -rf /tmp/.buildx-cache
              mv /tmp/.buildx-cache-new /tmp/.buildx-cache

          - name: Authenticate to Google Cloud
            uses: google-github-actions/auth@v1
            with:
              credentials_json: ${{ secrets.LOUIS_GAR_JSON_KEY }}
          - name: Deploy to Cloud Run
            # You may pin to the exact commit or the version.
            # uses: google-github-actions/deploy-cloudrun@e62f655d5754bec48078a72edc015367b01ee97b
            uses: google-github-actions/deploy-cloudrun@v1.0.2
            with:
              # Name of the container image to deploy (e.g. gcr.io/cloudrun/hello:latest). Required if not using a service YAML.
              image: ${{ secrets.LOUIS_REGISTRY }}/${{inputs.container-name}}:${{inputs.tag}}
              # ID of the service or fully qualified identifier for the service. Required if not using a service YAML.
              service: ${{inputs.container-name}}
              # Region in which the resource can be found.
              region: ${{ secrets.GCP_CLOUDRUN_REGION }}
              env_vars: ${{ secrets.ENV }}
