name: Docker GCP deployment

on:
  push:
    branches:
      - redat97/issue13
  workflow_dispatch:

jobs:
  lint-test:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
    secrets: inherit

  code-coverage:
    needs: lint-test
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install coverage pytest

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report --show-missing --fail-under=60

  build:
    needs: code-coverage
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-container.yml@main
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    needs: build
    uses: ai-cfia/github-workflows/.github/workflows/workflow-deploy-gcp.yml@main
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit