name: Docker GCP deployment

on:
    push:
        branches:
          - github-action-workflow
    workflow_dispatch:

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ruff pytest httpx
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    lint-test:
        needs: prepare
        uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
        secrets: inherit
